
- name: hostnameSet
  hostname: name={{ inventory_hostname }}
  when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')

- name: etcHhosts
  lineinfile:
    path: /etc/hosts
    line: "{{ hostvars[item].ansible_ssh_host }} {{ hostvars[item].inventory_hostname}}"
    backup: yes
  with_items: "{{ groups['all'] }}"

- name: disableSELinux
  selinux:
    state: disabled

- name: disableSwap
  command: swapoff -a

- name: fstabSwapoff
  replace:
    dest: /etc/fstab
    regexp: '^/dev/mapper/centos-swap'
    replace: '#/dev/mapper/centos-swap'

- name: createRepo
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: ["https://packages.cloud.google.com/yum/doc/yum-key.gpg", "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"]
    file: kubernetesEl7
    gpgcheck: yes

- name: installPackages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - kubeadm

- name: verifySerices
  service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - docker
    - kubelet
